### PR TITLE
1.20 support

### PR DESCRIPTION
**Pull request by Camotoy**
Not everything complies with the code style, but hopefully this is of some help. Of course, move the target branch to a new branch.

~~The items on the bargain statue GUI buttons don't render with some mod in a modpack, and I'm trying to figure out which mod that is. It works fine with no other mods/JEI, though.~~ Culprit is Inventory Profiles Next; there's already an issue for it, oops.

Also this is just about my first experience with Forge, so please excuse any possible mistake that would be a result of lack of knowledge.

### CODE REVIEW

**Review by joaobnobre — APPROVED** [review]
LGTM :D

**Comment by joaobnobre** [comment]
LGTM :D

**Review by joaobnobre — APPROVED** [review]

**Comment by Tictim** [comment]
Apologies for the long absent.

Many thanks for the work. Since there's another PR that accomplishes the same thing (#87) I will check out both of this and other PR to create final version for release. This version of 1.20.1 codebase will be only used temporarily, as I am currently attempting to rewrite this mod with Architectury template as a base; with goals of supporting Fabric loader and creating definitive and version-independent API for things like stamina system. Hope I can actually finish it this time 😅.

I don't have a clue for incompatibility with Inventory Profiles Next either. It is rather a strange issue. I'm thinking about just re-implementing the whole UI without using container screen as the base, but this might turn out to be more of a hassle than a simple solution.

**Comment by Camotoy** [comment]
I agree that not having the bargain screen extend Container probably the smartest solution, assuming the hassle is worth it. Plus, the JEI integration could probably be removed.

**Comment by Tictim** [comment]
Merged with 6ca9818.

**Pull request closed without merging**
